steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  env: ['PROJECT_ROOT=foo']
  args: ['build', '-o', 'hello-world', 'main.go']
- name: 'gcr.io/cloud-builders/docker'
  env: ['PROJECT_ROOT=foo']
  args: ['build', '--tag=asia.gcr.io/$PROJECT_ID/wdpress/hello-world:latest', '.']
images: ['asia.gcr.io/$PROJECT_ID/wdpress/hello-world:latest']